apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: askbias-update
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: askbias
    namespace: flux-system
  git:
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
    push:
      branch: main
  update:
    path: ./flux
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: askbias-repo
spec:
  image: mever/askbias
  interval: 10m
  secretRef:
    name: docker-hub-mever-creds
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: askbias-repo-policy
spec:
  imageRepositoryRef:
    name: askbias-repo
  filterTags:
    pattern: "^main-[a-f0-9]+-(?P<ts>[0-9,\\.,\\-]+)$"
    extract: "$ts"
  policy:
    alphabetical:
      order: asc
